name: Go
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Go Test
        run: make test

      - name: Go Build
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: check_hp_firmware
          path: build
